# Generated by Django 6.0 on 2025-12-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
