# Generated by Django 6.0 on 2025-12-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.TextField(default='None'),
        ),
    ]
