# Generated by Django 6.0 on 2025-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_student_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='info',
            field=models.TextField(),
        ),
    ]
